
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      #MYSQL_DATABASE: 'mycar'
      SERVER: '127.0.0.1'
      MYSQL_TCP_PORT: 3307
    ports: 
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 3
  
  mycar:
    build:
      context: .
    environment:
      DBHOST: mysql
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '3000:80'
        
volumes:
  db-volume: